services:
  mysql:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: multictactoe
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
